// src/pages/LandingPage.jsx - UPDATED WITH GUEST FLOW

import React from 'react';
import { useNavigate } from 'react-router-dom';
import { Briefcase, Calendar, Bot, Shield, Zap, TrendingUp, ArrowRight, Rocket } from 'lucide-react';

function LandingPage() {
  const navigate = useNavigate();

  const features = [
    {
      icon: <Bot className="w-8 h-8 text-blue-600" />,
      title: 'AI-Powered Matching',
      description: 'Advanced algorithms match you with the perfect job opportunities based on your skills and preferences.'
    },
    {
      icon: <Zap className="w-8 h-8 text-yellow-600" />,
      title: 'Auto-Apply',
      description: 'Automatically apply to relevant positions with personalized cover letters generated by AI.'
    },
    {
      icon: <Calendar className="w-8 h-8 text-green-600" />,
      title: 'Interview Scheduling',
      description: 'Seamlessly book interviews with automatic calendar integration and smart conflict detection.'
    },
    {
      icon: <Shield className="w-8 h-8 text-purple-600" />,
      title: 'Blockchain Verified',
      description: 'All applications recorded on BSC blockchain for transparent, verifiable proof of your job search.'
    },
    {
      icon: <TrendingUp className="w-8 h-8 text-red-600" />,
      title: 'Real-Time Tracking',
      description: 'Monitor application status, interview progress, and response rates in your personalized dashboard.'
    },
    {
      icon: <Briefcase className="w-8 h-8 text-indigo-600" />,
      title: 'Multi-Platform Scraping',
      description: 'Access jobs from LinkedIn, Indeed, AngelList and more - all in one unified platform.'
    }
  ];

  const stats = [
    { value: '10,000+', label: 'Jobs Matched' },
    { value: '5,000+', label: 'Applications Sent' },
    { value: '1,200+', label: 'Interviews Scheduled' },
    { value: '95%', label: 'Success Rate' }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100">
      {/* Navigation */}
      <nav className="bg-white shadow-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <div className="flex justify-between items-center">
            <div className="flex items-center gap-2">
              <Briefcase className="w-8 h-8 text-blue-600" />
              <span className="text-2xl font-bold text-gray-900">JobInt</span>
            </div>
            <div className="flex gap-4">
              <button
                onClick={() => navigate('/login')}
                className="px-4 py-2 text-gray-700 hover:text-gray-900 font-medium"
              >
                Login
              </button>
              <button
                onClick={() => navigate('/register')}
                className="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 font-medium"
              >
                Get Started
              </button>
            </div>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <div className="text-center">
          <h1 className="text-5xl md:text-6xl font-bold text-gray-900 mb-6">
            Your AI-Powered
            <span className="text-blue-600"> Job Search Assistant</span>
          </h1>
          <p className="text-xl text-gray-600 mb-8 max-w-3xl mx-auto">
            Automate your entire job application process with AI. From discovering opportunities 
            to scheduling interviews, JobInt handles it all while you focus on preparation.
          </p>
          
          {/* CTA Buttons */}
          <div className="flex gap-4 justify-center flex-wrap mb-6">
            <button
              onClick={() => navigate('/guest-apply')}
              className="px-8 py-4 bg-gradient-to-r from-blue-600 to-indigo-600 text-white rounded-lg hover:from-blue-700 hover:to-indigo-700 font-medium text-lg shadow-lg flex items-center gap-2"
            >
              <Rocket className="w-5 h-5" />
              Apply Now (No Signup)
            </button>
            <button
              onClick={() => navigate('/register')}
              className="px-8 py-4 bg-white text-gray-700 rounded-lg hover:bg-gray-50 font-medium text-lg shadow-lg"
            >
              Create Free Account
            </button>
          </div>
          
          <p className="text-sm text-gray-500">
            🚀 <strong>Guest Mode:</strong> Apply to jobs instantly without creating an account • Track with a simple token
          </p>
          
          <div className="mt-4 inline-flex items-center gap-2 px-4 py-2 bg-green-50 border border-green-200 rounded-lg">
            <Shield className="w-4 h-4 text-green-600" />
            <span className="text-sm text-green-800">
              <strong>New:</strong> Guest applications now verified on blockchain
            </span>
          </div>
        </div>

        {/* Stats */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-8 mt-20">
          {stats.map((stat, index) => (
            <div key={index} className="text-center">
              <div className="text-4xl font-bold text-blue-600 mb-2">{stat.value}</div>
              <div className="text-gray-600">{stat.label}</div>
            </div>
          ))}
        </div>
      </div>

      {/* Guest vs Account Comparison */}
      <div className="bg-white py-16">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold text-gray-900 mb-4">
              Choose Your Experience
            </h2>
            <p className="text-lg text-gray-600">
              Start as a guest or create an account for full features
            </p>
          </div>

          <div className="grid md:grid-cols-2 gap-8 max-w-5xl mx-auto">
            {/* Guest Mode */}
            <div className="border-2 border-gray-200 rounded-xl p-8 hover:border-blue-300 transition-all">
              <div className="text-center mb-6">
                <div className="inline-flex items-center justify-center w-16 h-16 bg-blue-100 rounded-full mb-4">
                  <Rocket className="w-8 h-8 text-blue-600" />
                </div>
                <h3 className="text-2xl font-bold text-gray-900 mb-2">Guest Mode</h3>
                <p className="text-gray-600">Perfect for quick applications</p>
              </div>
              
              <ul className="space-y-3 mb-6">
                <li className="flex items-start gap-2">
                  <ArrowRight className="w-5 h-5 text-green-600 flex-shrink-0 mt-0.5" />
                  <span className="text-gray-700">Submit applications instantly</span>
                </li>
                <li className="flex items-start gap-2">
                  <ArrowRight className="w-5 h-5 text-green-600 flex-shrink-0 mt-0.5" />
                  <span className="text-gray-700">Track with simple tokens</span>
                </li>
                <li className="flex items-start gap-2">
                  <ArrowRight className="w-5 h-5 text-green-600 flex-shrink-0 mt-0.5" />
                  <span className="text-gray-700">AI-generated cover letters</span>
                </li>
                <li className="flex items-start gap-2">
                  <ArrowRight className="w-5 h-5 text-green-600 flex-shrink-0 mt-0.5" />
                  <span className="text-gray-700">Blockchain verification</span>
                </li>
                <li className="flex items-start gap-2">
                  <ArrowRight className="w-5 h-5 text-gray-400 flex-shrink-0 mt-0.5" />
                  <span className="text-gray-400">Limited to 10 applications/day</span>
                </li>
              </ul>

              <button
                onClick={() => navigate('/guest-apply')}
                className="w-full py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 font-medium"
              >
                Apply as Guest
              </button>
            </div>

            {/* Full Account */}
            <div className="border-2 border-indigo-500 rounded-xl p-8 bg-gradient-to-br from-indigo-50 to-purple-50 relative">
              <div className="absolute -top-4 left-1/2 transform -translate-x-1/2">
                <span className="inline-block px-4 py-1 bg-indigo-600 text-white text-sm font-medium rounded-full">
                  Recommended
                </span>
              </div>
              
              <div className="text-center mb-6">
                <div className="inline-flex items-center justify-center w-16 h-16 bg-indigo-600 rounded-full mb-4">
                  <Briefcase className="w-8 h-8 text-white" />
                </div>
                <h3 className="text-2xl font-bold text-gray-900 mb-2">Full Account</h3>
                <p className="text-gray-600">Maximum automation & features</p>
              </div>
              
              <ul className="space-y-3 mb-6">
                <li className="flex items-start gap-2">
                  <ArrowRight className="w-5 h-5 text-green-600 flex-shrink-0 mt-0.5" />
                  <span className="text-gray-700">Everything in Guest Mode</span>
                </li>
                <li className="flex items-start gap-2">
                  <ArrowRight className="w-5 h-5 text-green-600 flex-shrink-0 mt-0.5" />
                  <span className="text-gray-700">Unlimited applications</span>
                </li>
                <li className="flex items-start gap-2">
                  <ArrowRight className="w-5 h-5 text-green-600 flex-shrink-0 mt-0.5" />
                  <span className="text-gray-700">Auto-matching job discovery</span>
                </li>
                <li className="flex items-start gap-2">
                  <ArrowRight className="w-5 h-5 text-green-600 flex-shrink-0 mt-0.5" />
                  <span className="text-gray-700">Calendar integration</span>
                </li>
                <li className="flex items-start gap-2">
                  <ArrowRight className="w-5 h-5 text-green-600 flex-shrink-0 mt-0.5" />
                  <span className="text-gray-700">Advanced analytics</span>
                </li>
                <li className="flex items-start gap-2">
                  <ArrowRight className="w-5 h-5 text-green-600 flex-shrink-0 mt-0.5" />
                  <span className="text-gray-700">Priority support</span>
                </li>
              </ul>

              <button
                onClick={() => navigate('/register')}
                className="w-full py-3 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 font-medium"
              >
                Create Free Account
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* Features Section */}
      <div id="features" className="bg-gray-50 py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold text-gray-900 mb-4">
              Everything You Need to Land Your Dream Job
            </h2>
            <p className="text-xl text-gray-600">
              Powerful features designed to save you time and increase your success rate
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature, index) => (
              <div
                key={index}
                className="p-6 bg-white rounded-xl border-2 border-gray-100 hover:border-blue-200 hover:shadow-lg transition-all"
              >
                <div className="mb-4">{feature.icon}</div>
                <h3 className="text-xl font-semibold text-gray-900 mb-2">
                  {feature.title}
                </h3>
                <p className="text-gray-600">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* How It Works */}
      <div className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold text-gray-900 mb-4">
              How It Works
            </h2>
            <p className="text-xl text-gray-600">
              Get started in just 3 simple steps
            </p>
          </div>

          <div className="grid md:grid-cols-3 gap-12">
            <div className="text-center">
              <div className="w-16 h-16 bg-blue-600 text-white rounded-full flex items-center justify-center text-2xl font-bold mx-auto mb-4">
                1
              </div>
              <h3 className="text-xl font-semibold text-gray-900 mb-2">
                Submit Your Application
              </h3>
              <p className="text-gray-600">
                Fill in job details and your information. No account needed - get started in seconds.
              </p>
            </div>

            <div className="text-center">
              <div className="w-16 h-16 bg-blue-600 text-white rounded-full flex items-center justify-center text-2xl font-bold mx-auto mb-4">
                2
              </div>
              <h3 className="text-xl font-semibold text-gray-900 mb-2">
                AI Processes & Submits
              </h3>
              <p className="text-gray-600">
                Our AI generates a personalized cover letter and submits your application with blockchain verification.
              </p>
            </div>

            <div className="text-center">
              <div className="w-16 h-16 bg-blue-600 text-white rounded-full flex items-center justify-center text-2xl font-bold mx-auto mb-4">
                3
              </div>
              <h3 className="text-xl font-semibold text-gray-900 mb-2">
                Track & Get Interviews
              </h3>
              <p className="text-gray-600">
                Use your tracking token to monitor status and receive interview invitations directly.
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* CTA Section */}
      <div className="bg-gradient-to-r from-blue-600 to-indigo-600 py-20">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-4xl font-bold text-white mb-6">
            Ready to Transform Your Job Search?
          </h2>
          <p className="text-xl text-blue-100 mb-8">
            Join thousands of job seekers who are landing interviews 10x faster with JobInt
          </p>
          <div className="flex gap-4 justify-center">
            <button
              onClick={() => navigate('/guest-apply')}
              className="px-8 py-4 bg-white text-blue-600 rounded-lg hover:bg-gray-100 font-medium text-lg shadow-lg inline-flex items-center gap-2"
            >
              <Rocket className="w-5 h-5" />
              Apply as Guest
            </button>
            <button
              onClick={() => navigate('/register')}
              className="px-8 py-4 bg-indigo-700 text-white rounded-lg hover:bg-indigo-800 font-medium text-lg shadow-lg inline-flex items-center gap-2"
            >
              Create Account
              <ArrowRight className="w-5 h-5" />
            </button>
          </div>
          <p className="text-blue-100 mt-4">
            No credit card required • Start for free
          </p>
        </div>
      </div>

      {/* Footer */}
      <footer className="bg-gray-900 text-white py-12">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid md:grid-cols-4 gap-8">
            <div>
              <div className="flex items-center gap-2 mb-4">
                <Briefcase className="w-6 h-6" />
                <span className="text-xl font-bold">JobInt</span>
              </div>
              <p className="text-gray-400">
                AI-powered job search automation platform
              </p>
            </div>
            <div>
              <h3 className="font-semibold mb-4">Product</h3>
              <ul className="space-y-2 text-gray-400">
                <li><a href="/" className="hover:text-white">Features</a></li>
                <li><a href="/" className="hover:text-white">Pricing</a></li>
                <li><a href="/" className="hover:text-white">FAQ</a></li>
              </ul>
            </div>
            <div>
              <h3 className="font-semibold mb-4">Company</h3>
              <ul className="space-y-2 text-gray-400">
                <li><a href="/" className="hover:text-white">About</a></li>
                <li><a href="/" className="hover:text-white">Blog</a></li>
                <li><a href="/" className="hover:text-white">Careers</a></li>
              </ul>
            </div>
            <div>
              <h3 className="font-semibold mb-4">Legal</h3>
              <ul className="space-y-2 text-gray-400">
                <li><a href="/" className="hover:text-white">Privacy</a></li>
                <li><a href="/" className="hover:text-white">Terms</a></li>
                <li><a href="/" className="hover:text-white">Security</a></li>
              </ul>
            </div>
          </div>
          <div className="border-t border-gray-800 mt-8 pt-8 text-center text-gray-400">
            <p>&copy; 2026 JobInt. All rights reserved.</p>
          </div>
        </div>
      </footer>
    </div>
  );
}

export default LandingPage;